### ISSUE TITLE
Minimize, maximize and close buttons unresponsive after pausing the video

### ISSUE THREAD

**Issue by Xurdejl** [Samillion/ModernZ#18]
The minimize, maximize, and close buttons become unresponsive after pausing a video. This issue doesn't always occur immediately after pausing. Entering and exiting full screen seems to make them work again.

**Comment by Samillion** [comment]
I'm unable to reproduce this, could you do the following please:
- Update MPV
- Produce a log with `--v --log-file=output.txt` (Attach the log file please, don't paste text)

When you're running it with `--v`, try to reproduce the problem so it's shown in the logs.

**Comment by Xurdejl** [comment]
here are the logs
[output.txt](https://github.com/user-attachments/files/17348323/output.txt)

**Comment by Samillion** [comment]
The most notable thing from your log is this:

```
[  27.389][d][osd] Spent 14.227 ms in osd_render (slow!)
```

From what I can tell, you used the seekbar, which generated thumbnails, paused, maximized, unpaused...etc Each time osc is initiated just fine:

```
[  26.077][d][modernz] osc_init

[  24.898][d][cplayer] Run command: disable-section, flags=64, args=[name="input"]
[  24.898][d][cplayer] Run command: disable-section, flags=64, args=[name="window-controls"]

[  25.240][d][cplayer] Run command: enable-section, flags=64, args=[name="input", flags=""]
[  25.240][d][cplayer] Run command: enable-section, flags=64, args=[name="window-controls", flags=""]

[  26.087][d][cplayer] Run command: script-binding, flags=73, args=[name="modernz/__keybinding2"]
```

Something is causing a high load which is causing this (osd_render => slow). I noticed some invalidated LUT

This is only happening for ModernZ OSC? Looking at the logs, nothing from ModernZ is erroring or not functioning as intended.

**Comment by Xurdejl** [comment]
Yes, I tried replicating it on the other fork, but it worked just fine

**Comment by Samillion** [comment]
This is weird, I tried to reproduce using your exact config and shaders, still wasn't able to.

If you don't mind testing something. Could you run it with `--border=yes` and see if it happens with native window controls?

As far as I can tell, the cause is due to high load, which is causing OSD elements in general to render slowly (as shown in your log), but you said this only happens on ModernZ.

Trying to pin down the accomplice basically.

**Comment by Xurdejl** [comment]
I tried it, and it doesn't happen with the native controls. I also realized that it's only the maximize and minimize buttons that become unresponsive

**Comment by Samillion** [comment]
Perfect. I'll create a branch and give you a script tomorrow to try and see if it continues to happen.

Thank you very much for testing this, my last request, could you give me your `mpv.conf` and `modernz.conf` as you have it now?

I want to adjust the code based on your configuration, and then identify the global factor to make sure it doesn't happen to anyone.

Honestly, I might re-write the window controls elements, since they're a modified version of past forks.

**Comment by Xurdejl** [comment]
sure, here are my files
[mpv.zip](https://github.com/user-attachments/files/17352671/mpv.zip)

**Comment by Samillion** [comment]
Could you try re-produce this version please:
https://github.com/Samillion/ModernZ/blob/devel_wc_bug/modernz.lua

If possible, produce a log `--v --log-file=output.txt`

**Comment by Samillion** [comment]
A bit off-topic, but in your `mpv.conf` you have this:
```editorconfig
directory-filter-types=video, audio
```

Does it actually add audio files to the playlist with the space? I merely ask because I had to remove the space between `video,` and `audio`, otherwise the option wasn't read correctly.
```editorconfig
directory-filter-types=video,audio
```

**Comment by Xurdejl** [comment]
> Could you try to re-produce the bug with this version please: https://github.com/Samillion/ModernZ/blob/devel_wc_bug/modernz.lua
> 
> If possible, produce a log `--v --log-file=output.txt`

[output.txt](https://github.com/user-attachments/files/17356610/output.txt)


> A bit off-topic, but in your `mpv.conf` you have this:
> 
> ```editorconfig
> directory-filter-types=video, audio
> ```
> 
> Does it actually add audio files to the playlist with the space? I merely ask because I had to remove the space between `video,` and `audio`, otherwise the option wasn't read correctly.
> 
> ```editorconfig
> directory-filter-types=video,audio
> ```

Oh, yes, it doesn't work. Thanks for pointing it out. I actually use a different player for music

**Comment by Samillion** [comment]
Checking your log right now. So the bug occurred again in that version, right?

> I actually use a different player for music

😱 You're cheating on mpv with another player? How could you? I'm calling the police.

**Comment by Samillion** [comment]
I'm honestly stumped. The logs show ModernZ functioning as intended without any warns.

If you search for the keyword slow in your log, you'll see that there is definitely slow downs in render, which I assume why it would cause this issue.

But what I'm stumped on is that it only happens on ModernZ for you.

I've asked the guys at irc, hopefully one will be able to guide me to what I'm not seeing.

**Comment by Samillion** [comment]
I just remembered a similar issue [here](https://github.com/Samillion/ModernZ/issues/2) that was resolved by updating mpv.

@Keith94 do you happen to remember which version you updated from? I want to try and locate the exact mpv git commit that resolved these issues, maybe it'll help me track this down better.

**Comment by Samillion** [comment]
Could you try this version please: https://github.com/Samillion/ModernZ/blob/wc_bug_a2/modernz.lua

Let me know if the bug is still happening.

**Comment by Xurdejl** [comment]
> I'm honestly stumped. The logs show ModernZ functioning as intended without any warns.
> 
> If you search for the keyword `slow` in your log, you'll see that there is definitely slow downs in render, which I assume why it would cause this issue in the OSC.
> 
> Examples from your log:
> 
> ```
> [   0.173][v][vo/gpu-next/libplacebo] Spent 106.777 ms enumerating instance extensions (slow!)
> [   0.388][v][vo/gpu-next/libplacebo] Spent 177.154 ms creating vulkan device (slow!)
> [   2.373][d][osd] Spent 53.591 ms in osd_render (slow!)
> ```
> 
> But what I'm stumped on is that it only happens on ModernZ for you.
> 
> I've asked the guys at irc, hopefully one will be able to guide me to what I'm not seeing.

idk, maybe there is something wrong with my pc, it's quite old.



> Could you try this version please: https://github.com/Samillion/ModernZ/blob/wc_bug_a2/modernz.lua
> 
> Let me know if the bug is still happening.

Tried with this and still happening

**Comment by Samillion** [comment]
> idk, maybe there is something wrong with my pc, it's quite old.

Nah, if it's only happening on ModernZ, then it's something I did wrong.

I apologize for asking you to test a lot, could you try this update please? https://github.com/Samillion/ModernZ/blob/wc_bug_a2/modernz.lua

**Comment by Xurdejl** [comment]
> I apologize for asking you to test a lot, could you try this update please? 

No worries. 

> https://github.com/Samillion/ModernZ/blob/wc_bug_a2/modernz.lua

Same problem here

**Comment by Samillion** [comment]
Last attempt of the day, I promise: https://github.com/Samillion/ModernZ/blob/wc_bug_a2/modernz.lua

**Comment by Xurdejl** [comment]
> Last attempt of the day, I promise: https://github.com/Samillion/ModernZ/blob/wc_bug_a2/modernz.lua

Still happening.

I noticed that normally it fixes itself if I let the osc hide.

**Comment by Samillion** [comment]
Thank you so much for all the tests.

> I noticed that normally it fixes itself if I let the osc hide.

I adjusted the code. Whenever you're able to test, please. Bug still occurs?
https://github.com/Samillion/ModernZ/blob/wc_bug_a2/modernz.lua

**Comment by Xurdejl** [comment]
yes, still occurs

**Comment by Samillion** [comment]
Last version: https://github.com/Samillion/ModernZ/blob/wc_bug_a2/modernz.lua

In this one you'll notice the title and controls are smaller.

If this doesn't fix it, I'll have to ask for some guidance, so it might take a while. Hopefully this fixes it though.

**Comment by Keith94** [comment]
I can reproduce the issue too with the above linked script. Using latest mpv 4ab1ab8 built on Oct 14 2024

**Comment by Samillion** [comment]
Well, crap.

I'll sit down tomorrow and re-write a whole lot.

**Comment by Samillion** [comment]
Could you try this version and see if it's fixed in it, please:
https://github.com/Samillion/ModernZ/blob/wc_bug_rewrite/modernz.lua

This is a dev version, if you notice any other bugs other than the already opened issues, please let me know.

https://github.com/Samillion/ModernZ/commit/1c523201349e662511967a33868d7f997e5c2a34
```
An attempt to fix Window controls not functioning:
- Re-wrote in a consistent string format for osc_styles
- Properly use full ASS tags to eliminate unclosed ones
- Add areas to control show/hide better
- Observe title-bar property

Other fixes:
- Fix unnecessary deadzone above OSC
- Fix interactive playlist hiding behind OSC if video is paused
```

If the bug still persists, may I ask for a favor? I apologize for the burden, only if it's not a bother.

Could you record a video showcasing the bug? I want to reproduce with the exact steps.

**Comment by Samillion** [comment]
I applied the alpha cache https://github.com/Samillion/ModernZ/commit/fe5bc33b8171cd00664f04e30e76d8f4dcb1ffae 

Please let me know if the bug occurs.

**Comment by Keith94** [comment]
I can still reproduce it but i'll record something in a bit

**Comment by Samillion** [comment]
I reverted cache, it introduced new problems.

**Comment by Samillion** [comment]
I added tracing for window controls so that it would show up in the log
https://github.com/Samillion/ModernZ/blob/wc_bug_rewrite/modernz.lua

Could you please upload a log with the bug occuring in it? Again, apologies for all the requests, and I appreciate all the testing.

**Comment by Keith94** [comment]
[output.txt](https://github.com/user-attachments/files/17366115/output.txt)

https://github.com/user-attachments/assets/48c61a5b-4984-4b31-916a-ed970e9c9654

the window title and controls also don't show up in fullscreen, only shows up in borderless (pinned window)

https://github.com/user-attachments/assets/b1d68dd1-6516-4c33-9a9a-f36b175d1320

double click the window controls toggle fullscreen (basically the clicks go right through)

https://github.com/user-attachments/assets/21d9a820-31c9-4361-b73d-8716f2281e8c

when the maximize button works, first time you activate it, it jumps by a few pixels. not sure why

**Comment by Samillion** [comment]
I can finally reproduce this, thank you so much.

Video with low volume commentary lol (ignore cursor position, it's weird in there)

https://github.com/user-attachments/assets/87bf5e1e-93d9-4d22-9aef-5b4fb4a4183e

**Comment by Keith94** [comment]
Yeah it's a weird one! Buttons work flawlessly if you never pause the video. 🤣 

Hope that helps!

**Comment by Samillion** [comment]
I've come across a wall, because I'm able to reproduce the window controls/pixels bug on stock mpv

To reproduce, do the following:
- `mpv video.mp4 --no-border --no-config`
- Maximize => Fullscreen => Unmaximize
- Maximize => Unmiximize (now requires two clicks)

https://github.com/user-attachments/assets/5c3a02d5-13cb-4d71-87e2-fea6275587fd

I was checking all code, calculations, then I decided to check and bam. Are you guys able to re-produce it as well on stock?

**Comment by Keith94** [comment]
Yeah I can reproduce it as well following your steps.

**Comment by Samillion** [comment]
This is good news, because now I can blame someone else, which is good for my self esteem. 🤣 

I've left a note to the guys on irc, and I'll open an issue later on mpv's repo.

**Comment by Keith94** [comment]
Makes me wonder if that's separate than what's been raised here or if it's the same.

Can you reproduce bug mentioned in OP with these steps?

1. Open video file
2. Pin window using the button (`showontop=yes`)
3. Pause playback
4. Click maximize button

Result: window controls won't respond to clicks

**Comment by Keith94** [comment]
If you set `bottomhover=no` and try my steps above, I can get the bug to happen.

**Comment by Samillion** [comment]
Aha! Ok, let me try real quick, was about to post a video that I couldn't reproduce.

https://github.com/user-attachments/assets/896332f0-bd28-4622-82e9-95b3148a5a32

Will try now.

Side note: stupid cursor showing in the wrong place in my videos. Y u do dis cursor.

**Comment by Samillion** [comment]
> If you set bottomhover=no and try my steps above, I can get the bug to happen.

Ok, this is great, now I can finally reproduce the reported bug accurately, thank you very much for your constant help.

**Comment by Keith94** [comment]
No worries and happy to help. Such a weirdly specific bug so it took a while to track down lol.

**Comment by Samillion** [comment]
Hopefully this should fix it https://github.com/Samillion/ModernZ/blob/devel_wc_pin_rc/modernz.lua

@Keith94 @Xurdejl Could you try the new version please?

I've applied the other fixes as well: https://github.com/Samillion/ModernZ/commit/833340d3597935b6dd725a1e1bd4adb5c32a6823

Fix:
- Window controls not working on pin while paused
- Interactive playlist (lists) hiding behind OSC when paused
- Re-write osc_styles with consistent formatting to ensure ASS tag closures
- Consider: Keeping margins checks, not necessary at the moment. Decided in future.

**Comment by Xurdejl** [comment]
> Hopefully this should fix it https://github.com/Samillion/ModernZ/blob/devel_wc_pin_rc/modernz.lua

It seems that this version fixed the problem.

**Comment by Samillion** [comment]
Awesome! Once I was able to reproduce the steps exactly, it was easier to track down. I'll wait for Keith to confirm as well, then I will merge the fix to main and make a new release.

**Comment by Keith94** [comment]
LGTM 👍

**Comment by Keith94** [comment]
But I think you broke the alpha of the window title bar in fullscreen mode

**Comment by Samillion** [comment]
Should be good in here: https://github.com/Samillion/ModernZ/blob/devel_wc_release/modernz.lua

**Comment by Keith94** [comment]
> Should be good in here: https://github.com/Samillion/ModernZ/blob/devel_wc_release/modernz.lua

Hmmm I still don't see any fade in fullscreen with this one...

**Comment by Samillion** [comment]
That is weird, ok, could you show me the options you have in modernz.conf that are different from default? I'll try to reproduce that.

Fade works fine for me:

https://github.com/user-attachments/assets/7b54267d-674b-4ab0-b746-bd5da72b8f01

**Comment by Keith94** [comment]
Leave the window unpinned (the default behavior) and press F to go fullscreen. Does the fade work?

In your video you have it pinned (works as intended) but only unpinned has the issue

I tested with stock settings.

**Comment by Samillion** [comment]
It does work for me, yeah. Weird.

https://github.com/user-attachments/assets/f116916b-e296-4f9b-bd67-ab05fb44d400

**Comment by Keith94** [comment]
Damn something must be up on my end. Otherwise looks good!

**Comment by Samillion** [comment]
I'll do some more testing before merging into main. If it's happening on your end, means something is not working as it should.

I just need to track it down or be able to re-produce it.

**Comment by Keith94** [comment]
Just so we're on the same page, the bug doesn't happen if you put --no-border. Can you try again without no-border please.

**Comment by Samillion** [comment]
Damn, that is a nice catch. It is definitely remnants of the past due to a logic that didn't address that specific scenario. I bet this goes back to the previous fork.

Should be fixed here:
https://github.com/Samillion/ModernZ/blob/devel_wc_release/modernz.lua

Compare the change that you found and now fixed:
https://github.com/Samillion/ModernZ/blob/644a529e9c5919cfd126d5ae48661646a8fa9b1c/modernz.lua#L1249

To how it was in the [previous fork](https://github.com/zydezu/ModernX/blob/025a70395fa9947a9677da69630f13b8502030b0/modernx.lua#L2250])

```lua
if not user_opts.titleBarStrip and not state.border then
```

**Comment by Samillion** [comment]
Once you confirm, I'll work on the other issues, then I'll merge and release. Definitely adding you to credits in the next release.

**Comment by Samillion** [comment]
Fixed in #22

**Comment by Keith94** [comment]
That's great! And congrats on being the first person to report it 😛
