### ISSUE TITLE
Right click doesn't register above OSC

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#20]
![mpv_4uS5AC2CUO](https://github.com/user-attachments/assets/0d80e8a4-ae88-46ee-8aa8-696b71d1228a)

In the screenshot, the space between the seekbar and my mouse cursor acts like a dead zone where right mouse click won't do anything to pause/unpause.

**Comment by Samillion** [comment]
Yes and no. This area is a the top end of the OSC controls layer (count the title, even if hidden).

It should change if title is hidden. Will fix.

**Comment by Samillion** [comment]
Could you try this version and see if it's fixed in it, please:
https://github.com/Samillion/ModernZ/blob/wc_bug_rewrite/modernz.lua

This is a dev version, if you notice any other bugs other than the already opened issues, please let me know.

**Comment by Keith94** [comment]
I tested with 59303404078ffd95a32568bbc13af51de371f21a and can still reproduce :(

**Comment by Keith94** [comment]
In that version, the window title and window controls don't show up at all

**Comment by Samillion** [comment]
Could you try again please, I reverted a bit of code.

**Comment by Keith94** [comment]
https://github.com/user-attachments/assets/4ef88641-3ac9-453b-a685-5f8682cb6f34

blue dot is my right click; you can see where it works and doesn't

**Comment by Keith94** [comment]
Does it work properly for you? @Samillion

**Comment by Samillion** [comment]
It works exactly as you shown on the last video. I've reduced the deadzone above the OSC, so that once you reach the alpha fade, you're in "controller" zone. If that makes sense (ie: show osc).

**Comment by Keith94** [comment]
Oh I see. i guess I expected it to work like the stock OSC, where your inputs will register even 1 pixel above the OSC like below. in modernz there is approx 65 pixel gap where inputs don't work, but since the stock OSC doesn't have any fade, I suppose this makes sense why it works differently.

https://github.com/user-attachments/assets/edf64428-1c87-4791-81a7-75c0f9ab553b

**Comment by Samillion** [comment]
Can always improve it to be exact and count the deadzone based if title above OSC is shown or not.

Noted, though this might take a while, since the other things have been driving me mad 🥲

**Comment by Keith94** [comment]
In the case that it's difficult to fix, can always ship it the way it is. It's not hurting anybody and users can adapt to how it works

**Comment by Samillion** [comment]
I can make it so that it uses the `title` area as a trigger instead of the alpha shade area.

So that only when you hover the mouse in the line the title would be, it shows, anything above it is unaffected.

The main purpose for that deadzone is: the title is functional. A very niche/specific function, that I personally never use, but exist in almost all OSCs, even stock.

**Title above seekbar function:** 
- `Left click` => show `media-title` in OSD
- `Right click` => show `filename` in OSD

**Comment by Keith94** [comment]
Cool, I'd be willing to test it. I can understand the title should stay functional. I just thought it was weird that the control layer counted the title even if it was hidden (like you said earlier) haha.

**Comment by Samillion** [comment]
I'll tinker with it a bit later, and I'll try to utilize your idea of based it on OSCfadealpha and existence of title.

**Comment by Samillion** [comment]
Ok, now that all the other issues are fixed and release of [v0.1.2](https://github.com/Samillion/ModernZ/releases/tag/v0.1.2) is done (you're mentioned there btw), I'll focus on this to try and improve it.

I still haven't thought of the best way to do this, because alpha shade is non-linear. Once I do though, I'll apply the changes.

**Comment by Keith94** [comment]
That's wicked man! Thanks for all these updates

I think the script is pretty much bullet proof at this point. Should make it into mpv project one day (fingers crossed) 😆

**Comment by Samillion** [comment]
Ok, back to this since I have some time to focus on it.

Suggested solution:
- If title above seekbar = no, decrease deadzone accordingly.

Would that be an acceptable solution?

**Comment by Keith94** [comment]
>If title above seekbar = no, decrease deadzone accordingly.

Sounds good to me!

**Comment by Samillion** [comment]
I'll also add a user_opt to adjust the value of bottomhover (at the moment it's 160). That way, you can refine it to your exact liking.
